/**
 * Определения всех достижений
 */

export const ACHIEVEMENTS = {
  // Первые достижения
  first_join: {
    id: 'first_join',
    name: '🎤 Малыш заговорил',
    description: 'Присоединился к голосовому каналу впервые',
    points: 10,
    condition: (stats) => stats.total_sessions >= 1,
  },
  first_afk: {
    id: 'first_afk',
    name: '😴 Первый сон',
    description: 'Был перемещен в AFK впервые',
    points: 5,
    condition: (stats) => stats.total_afk_moves >= 1,
  },
  first_message: {
    id: 'first_message',
    name: '💬 Первые буквы',
    description: 'Отправил первое сообщение в текстовом канале',
    points: 10,
    condition: (stats) => stats.messages_sent >= 1,
  },
  first_settings: {
    id: 'first_settings',
    name: '⚙️ Первые настройки',
    description: 'Изменил настройки бота впервые',
    points: 10,
    condition: (stats) => stats.settings_changes >= 1,
  },
  first_web_visit: {
    id: 'first_web_visit',
    name: '🌐 Первый серфер',
    description: 'Посетил веб-панель бота впервые',
    points: 15,
    condition: (stats) => stats.web_visits >= 1,
  },
  first_stream: {
    id: 'first_stream',
    name: '📡 Первый стример',
    description: 'Включил трансляцию впервые',
    points: 20,
    condition: (stats) => stats.total_streams >= 1,
  },

  // Голосовые каналы
  voice_starter: {
    id: 'voice_starter',
    name: '🎧 Алло, это я',
    description: 'Провел 50+ часов в голосовых каналах',
    points: 50,
    condition: (stats) => stats.total_voice_time >= 50 * 3600,
  },
  voice_addict: {
    id: 'voice_addict',
    name: '🎧 Заболтал до сотки',
    description: 'Провел 100+ часов в голосовых каналах',
    points: 100,
    condition: (stats) => stats.total_voice_time >= 100 * 3600,
  },

  voice_god: {
    id: 'voice_god',
    name: '🎧 Звезда эфира',
    description: 'Провел 1000+ часов в голосовых каналах',
    points: 1000,
    condition: (stats) => stats.total_voice_time >= 1000 * 3600,
  },

  // Сообщения
  chatty_beginner: {
    id: 'chatty_beginner',
    name: '💬 Разговорчивый новичок',
    description: 'Отправил 200+ сообщений в текстовых каналах',
    points: 25,
    condition: (stats) => stats.messages_sent >= 200,
  },
  chatty_user: {
    id: 'chatty_user',
    name: '💬 Болтун',
    description: 'Отправил 500+ сообщений в текстовых каналах',
    points: 75,
    condition: (stats) => stats.messages_sent >= 500,
  },
  flooter: {
    id: 'flooter',
    name: '💬 Флудер',
    description: 'Отправил 750+ сообщений в текстовых каналах',
    points: 100,
    condition: (stats) => stats.messages_sent >= 750,
  },
  linguist: {
    id: 'linguist',
    name: '💬 Лингвист',
    description: 'Отправил 1000+ сообщений в текстовых каналах',
    points: 150,
    condition: (stats) => stats.messages_sent >= 1000,
  },

  // Сессии
  session_beginner: {
    id: 'session_beginner',
    name: '🎯 Начинающий участник',
    description: 'Участвовал в 10+ голосовых сессиях',
    points: 15,
    condition: (stats) => stats.total_sessions >= 10,
  },
  session_veteran: {
    id: 'session_veteran',
    name: '🎯 Опытный участник',
    description: 'Участвовал в 50+ голосовых сессиях',
    points: 40,
    condition: (stats) => stats.total_sessions >= 50,
  },
  session_master: {
    id: 'session_master',
    name: '🎯 Мастер сессий',
    description: 'Участвовал в 100+ голосовых сессиях',
    points: 75,
    condition: (stats) => stats.total_sessions >= 100,
  },
  frequent_guest: {
    id: 'frequent_guest',
    name: '🎯 Частый гость',
    description: 'Участвовал в 200+ голосовых сессиях',
    points: 150,
    condition: (stats) => stats.total_sessions >= 200,
  },
  permanent_resident: {
    id: 'permanent_resident',
    name: '🎯 Постоянный житель',
    description: 'Участвовал в 500+ голосовых сессиях',
    points: 350,
    condition: (stats) => stats.total_sessions >= 500,
  },
  session_lord: {
    id: 'session_lord',
    name: '🎯 Властелин сессий',
    description: 'Участвовал в 1000+ голосовых сессиях',
    points: 1000,
    condition: (stats) => stats.total_sessions >= 1000,
  },

  // AFK
  afk_beginner: {
    id: 'afk_beginner',
    name: '😴 AFK новичок',
    description: 'Перемещен в AFK 10 раз',
    points: 10,
    condition: (stats) => stats.total_afk_moves >= 10,
  },
  afk_veteran: {
    id: 'afk_veteran',
    name: '😴 AFK ветеран',
    description: 'Перемещен в AFK 50 раз',
    points: 50,
    condition: (stats) => stats.total_afk_moves >= 50,
  },
  afk_master: {
    id: 'afk_master',
    name: '😴 AFK Специалист',
    description: 'Перемещен в AFK 100 раз',
    points: 100,
    condition: (stats) => stats.total_afk_moves >= 100,
  },
  afk_time_lord: {
    id: 'afk_time_lord',
    name: '😴 AFK Повелитель времени',
    description: 'Провел 1000+ часов в AFK канале',
    points: 1000,
    condition: (stats) => stats.total_afk_time >= 1000 * 3600,
  },
  no_afk_week: {
    id: 'no_afk_week',
    name: '💪 Железная воля',
    description: 'Неделя без перемещений в AFK',
    points: 50,
    condition: (stats) => false, // Специальная логика
  },

  // Другие
  mute_master: {
    id: 'mute_master',
    name: '🎙️ Мастер тишины',
    description: 'Переключил микрофон 100 раз',
    points: 25,
    condition: (stats) => stats.total_mute_toggles >= 100,
  },
  long_session: {
    id: 'long_session',
    name: '⏰ Марафонец',
    description: 'Провел 12+ часов в одной сессии',
    points: 75,
    condition: (stats) => stats.longest_session >= 12 * 3600,
  },
  voice_vegetable: {
    id: 'voice_vegetable',
    name: '🥦 Биомебель войса',
    description: 'Провел 24+ часов в одной сессии',
    points: 150,
    condition: (stats) => stats.longest_session >= 24 * 3600,
  },
  settings_explorer: {
    id: 'settings_explorer',
    name: '⚙️ Исследователь настроек',
    description: 'Изменил настройки бота 20 раз',
    points: 30,
    condition: (stats) => stats.settings_changes >= 20,
  },
  mention_responder: {
    id: 'mention_responder',
    name: '📢 Отзывчивый',
    description: 'Ответил на 1000+ упоминаний',
    points: 100,
    condition: (stats) => stats.mentions_responded >= 1000,
  },

  // Стримы
  stream_viewer_1: {
    id: 'stream_viewer_1',
    name: '📺 Одним глазком',
    description: 'Провел 5+ часов в канале Че смотрим?',
    points: 10,
    condition: (stats) => stats.stream_channel_time >= 5 * 3600,
  },
  stream_viewer_2: {
    id: 'stream_viewer_2',
    name: '📺 Зритель со стажем',
    description: 'Провел 50+ часов в канале Че смотрим?',
    points: 50,
    condition: (stats) => stats.stream_channel_time >= 50 * 3600,
  },
  stream_viewer_3: {
    id: 'stream_viewer_3',
    name: '📺 Топовый зритель',
    description: 'Провел 100+ часов в канале Че смотрим?',
    points: 100,
    condition: (stats) => stats.stream_channel_time >= 100 * 3600,
  },
  stream_viewer_4: {
    id: 'stream_viewer_4',
    name: '📺 Киберфанат',
    description: 'Провел 200+ часов в канале Че смотрим?',
    points: 200,
    condition: (stats) => stats.stream_channel_time >= 200 * 3600,
  },
  stream_viewer_5: {
    id: 'stream_viewer_5',
    name: '📺 Бессмертный зритель',
    description: 'Провел 500+ часов в канале Че смотрим?',
    points: 500,
    condition: (stats) => stats.stream_channel_time >= 500 * 3600,
  },
  stream_viewer_6: {
    id: 'stream_viewer_6',
    name: '📺 Легенда трансляций',
    description: 'Провел 1000+ часов в канале Че смотрим?',
    points: 1000,
    condition: (stats) => stats.stream_channel_time >= 1000 * 3600,
  },

  // Cheater Checker — проверенные профили
  checker_first: {
    id: 'checker_first',
    name: '🔍 Досье открыто',
    description: 'Проверил первый Steam-профиль',
    points: 5,
    condition: (stats) => stats.totalChecked >= 1,
  },
  checker_beginner: {
    id: 'checker_beginner',
    name: '🔍 Любопытный сосед',
    description: 'Проверил 10 Steam-профилей',
    points: 10,
    condition: (stats) => stats.totalChecked >= 10,
  },
  checker_active: {
    id: 'checker_active',
    name: '🔍 Любитель покопаться',
    description: 'Проверил 25 Steam-профилей',
    points: 25,
    condition: (stats) => stats.totalChecked >= 25,
  },
  checker_veteran: {
    id: 'checker_veteran',
    name: '🔍 Диванный детектив',
    description: 'Проверил 50 Steam-профилей',
    points: 50,
    condition: (stats) => stats.totalChecked >= 50,
  },
  checker_master: {
    id: 'checker_master',
    name: '🔍 Маленький сыщик',
    description: 'Проверил 100 Steam-профилей',
    points: 100,
    condition: (stats) => stats.totalChecked >= 100,
  },
  checker_300: {
    id: 'checker_300',
    name: '🔍 Патруль на минималках',
    description: 'Проверил 300 Steam-профилей',
    points: 200,
    condition: (stats) => stats.totalChecked >= 300,
  },
  checker_500: {
    id: 'checker_500',
    name: '🔍 Машина подозрений',
    description: 'Проверил 500 Steam-профилей',
    points: 350,
    condition: (stats) => stats.totalChecked >= 500,
  },
  checker_700: {
    id: 'checker_700',
    name: '🔍 Главный по репортам',
    description: 'Проверил 700 Steam-профилей',
    points: 500,
    condition: (stats) => stats.totalChecked >= 700,
  },
  checker_1000: {
    id: 'checker_1000',
    name: '🔍 Параноик года',
    description: 'Проверил 1000 Steam-профилей',
    points: 750,
    condition: (stats) => stats.totalChecked >= 1000,
  },

  // Cheater Checker — выявленные читеры
  cheater_found_first: {
    id: 'cheater_found_first',
    name: '🚨 Я так и знал',
    description: 'Выявил первого читера',
    points: 15,
    condition: (stats) => stats.bannedFound >= 1,
  },
  cheater_found_5: {
    id: 'cheater_found_5',
    name: '🚨 Крысолов',
    description: 'Выявил 5 читеров',
    points: 25,
    condition: (stats) => stats.bannedFound >= 5,
  },
  cheater_found_10: {
    id: 'cheater_found_10',
    name: '🚨 Слишком много совпадений',
    description: 'Выявил 10 читеров',
    points: 50,
    condition: (stats) => stats.bannedFound >= 10,
  },
  cheater_found_25: {
    id: 'cheater_found_25',
    name: '🚨 Минус аккаунт',
    description: 'Выявил 25 читеров',
    points: 150,
    condition: (stats) => stats.bannedFound >= 25,
  },
  cheater_found_50: {
    id: 'cheater_found_50',
    name: '🚨 Уже не удивляюсь',
    description: 'Выявил 50 читеров',
    points: 300,
    condition: (stats) => stats.bannedFound >= 50,
  },
  cheater_found_100: {
    id: 'cheater_found_100',
    name: '🚨 Санитар матчмейкинга',
    description: 'Выявил 100 читеров',
    points: 450,
    condition: (stats) => stats.bannedFound >= 100,
  },
  cheater_found_300: {
    id: 'cheater_found_300',
    name: '🚨 Истребитель шнырей',
    description: 'Выявил 300 читеров',
    points: 600,
    condition: (stats) => stats.bannedFound >= 300,
  },
  cheater_found_500: {
    id: 'cheater_found_500',
    name: '🚨 Valve мне должны',
    description: 'Выявил 500 читеров',
    points: 800,
    condition: (stats) => stats.bannedFound >= 500,
  },
  cheater_found_700: {
    id: 'cheater_found_700',
    name: '🚨 У меня нет жизни, но есть статистика',
    description: 'Выявил 700 читеров',
    points: 900,
    condition: (stats) => stats.bannedFound >= 700,
  },
  cheater_found_1000: {
    id: 'cheater_found_1000',
    name: '🚨 VAC на ножках',
    description: 'Выявил 1000 читеров',
    points: 1000,
    condition: (stats) => stats.bannedFound >= 1000,
  },

  // Bot Checker — проверенные боты
  bot_check_first: {
    id: 'bot_check_first',
    name: '🔍 Заглянул под капот',
    description: 'Проверил первого бота',
    points: 5,
    condition: (stats) => stats.botTotalChecked >= 1,
  },
  bot_check_beginner: {
    id: 'bot_check_beginner',
    name: '🔍 Ревизия железа',
    description: 'Проверил 10 ботов',
    points: 10,
    condition: (stats) => stats.botTotalChecked >= 10,
  },
  bot_check_active: {
    id: 'bot_check_active',
    name: '🔍 Беседа с тостером',
    description: 'Проверил 25 ботов',
    points: 25,
    condition: (stats) => stats.botTotalChecked >= 25,
  },
  bot_check_veteran: {
    id: 'bot_check_veteran',
    name: '🔍 Считаю транзисторы',
    description: 'Проверил 50 ботов',
    points: 50,
    condition: (stats) => stats.botTotalChecked >= 50,
  },
  bot_check_master: {
    id: 'bot_check_master',
    name: '🔍 Спорю с микроволновкой',
    description: 'Проверил 100 ботов',
    points: 100,
    condition: (stats) => stats.botTotalChecked >= 100,
  },
  bot_check_300: {
    id: 'bot_check_300',
    name: '🔍 Психотерапевт для роботов',
    description: 'Проверил 300 ботов',
    points: 200,
    condition: (stats) => stats.botTotalChecked >= 300,
  },
  bot_check_500: {
    id: 'bot_check_500',
    name: '🔍 Философ с мультиваркой',
    description: 'Проверил 500 ботов',
    points: 350,
    condition: (stats) => stats.botTotalChecked >= 500,
  },
  bot_check_700: {
    id: 'bot_check_700',
    name: '🔍 Собеседник пылесоса',
    description: 'Проверил 700 ботов',
    points: 500,
    condition: (stats) => stats.botTotalChecked >= 700,
  },
  bot_check_1000: {
    id: 'bot_check_1000',
    name: '🔍 Дрессировщик холодильников',
    description: 'Проверил 1000 ботов',
    points: 750,
    condition: (stats) => stats.botTotalChecked >= 1000,
  },

  // Bot Checker — выявленные боты
  bot_found_first: {
    id: 'bot_found_first',
    name: '🗑️ Поймал за проводами',
    description: 'Выявил первого бота',
    points: 15,
    condition: (stats) => stats.botBannedFound >= 1,
  },
  bot_found_5: {
    id: 'bot_found_5',
    name: '🗑️ Выключатель питания',
    description: 'Выявил 5 ботов',
    points: 25,
    condition: (stats) => stats.botBannedFound >= 5,
  },
  bot_found_10: {
    id: 'bot_found_10',
    name: '🗑️ Контролёр розеток',
    description: 'Выявил 10 ботов',
    points: 50,
    condition: (stats) => stats.botBannedFound >= 10,
  },
  bot_found_25: {
    id: 'bot_found_25',
    name: '🗑️ Сборщик металлолома',
    description: 'Выявил 25 ботов',
    points: 150,
    condition: (stats) => stats.botBannedFound >= 25,
  },
  bot_found_50: {
    id: 'bot_found_50',
    name: '🗑️ Мясорубка для ИИ',
    description: 'Выявил 50 ботов',
    points: 300,
    condition: (stats) => stats.botBannedFound >= 50,
  },
  bot_found_100: {
    id: 'bot_found_100',
    name: '🗑️ Санитар серверной',
    description: 'Выявил 100 ботов',
    points: 450,
    condition: (stats) => stats.botBannedFound >= 100,
  },
  bot_found_300: {
    id: 'bot_found_300',
    name: '🗑️ Истребитель бездушных',
    description: 'Выявил 300 ботов',
    points: 600,
    condition: (stats) => stats.botBannedFound >= 300,
  },
  bot_found_500: {
    id: 'bot_found_500',
    name: '🗑️ Палач машинного смысла',
    description: 'Выявил 500 ботов',
    points: 800,
    condition: (stats) => stats.botBannedFound >= 500,
  },
  bot_found_700: {
    id: 'bot_found_700',
    name: '🗑️ Апокалипсис роботов',
    description: 'Выявил 700 ботов',
    points: 900,
    condition: (stats) => stats.botBannedFound >= 700,
  },
  bot_found_1000: {
    id: 'bot_found_1000',
    name: '🗑️ Судный день для ИИ',
    description: 'Выявил 1000 ботов',
    points: 1000,
    condition: (stats) => stats.botBannedFound >= 1000,
  },

  // Специальные
  best_admin: {
    id: 'best_admin',
    name: '👑 Kakashech - Лучший админ',
    description: 'Лучший admin_ebaniy канала',
    points: 0,
    condition: (stats) => false, // Выдается вручную
  },
};
